services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: rental-aggregator-db
    environment:
      POSTGRES_DB: rental_aggregator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rental_aggregator"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: rental-aggregator-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass redis123
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Python FastAPI Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: rental-aggregator-api
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-production}
      DEBUG: ${DEBUG:-false}
      PORT: 8000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: rental_aggregator
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD:-password123}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis123}
      FIRECRAWL_API_KEY: ${FIRECRAWL_API_KEY:-}
      FIRECRAWL_BASE_URL: ${FIRECRAWL_BASE_URL:-https://api.firecrawl.dev}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      CACHE_TTL_SECONDS: ${CACHE_TTL_SECONDS:-3600}
      CSV_EXPORT_DIR: ${CSV_EXPORT_DIR:-csv_exports}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - logs_data:/app/logs
      - csv_exports_data:/app/csv_exports
    restart: unless-stopped

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: rental-aggregator-api-dev
    environment:
      ENVIRONMENT: development
      DEBUG: true
      PORT: 8000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: rental_aggregator
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD:-password123}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis123}
      FIRECRAWL_API_KEY: ${FIRECRAWL_API_KEY:-}
      FIRECRAWL_BASE_URL: ${FIRECRAWL_BASE_URL:-https://api.firecrawl.dev}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      CACHE_TTL_SECONDS: ${CACHE_TTL_SECONDS:-3600}
      CSV_EXPORT_DIR: ${CSV_EXPORT_DIR:-csv_exports}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
      - ./csv_exports:/app/csv_exports
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    profiles:
      - dev

  # Redis Commander (Optional - for Redis GUI)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: rental-aggregator-redis-gui
    environment:
      REDIS_HOSTS: local:redis:6379:0:redis123
    ports:
      - "8081:8081"
    depends_on:
      - redis
    profiles:
      - tools

  # pgAdmin (Optional - for PostgreSQL GUI)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rental-aggregator-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rental-aggregator.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local
  logs_data:
    driver: local
  csv_exports_data:
    driver: local

networks:
  default:
    name: rental-aggregator-network
